### ISSUE TITLE
About hardware

### ISSUE THREAD

**Issue by AlejandroSilvestri** [poine/rosmip#1]
@poine 

I'm impressed with the videos from your channel.

Do you have a fixed top camera for tracking?

Does the vehicle have a wireless connection for navigation?

What hardware are you using?

Thank you very much!

**Comment by poine** [comment]
On Wed, Dec 6, 2017 at 1:55 PM, AlejandroSilvestri <notifications@github.com
> wrote:

> @poine <https://github.com/poine>
>
> I'm impressed with the videos from your channel.
>
> Do you have a fixed top camera for tracking?
>

yes - https://github.com/poine/smocap


> Does the vehicle have a wireless connection for navigation?
>
yes - wifi


> What hardware are you using?
>
beaglebone blue - it is only running the low level control - the rest runs
on an I7 groundstation. I might work on getting more onboard when time
allows


> Thank you very much!
>
You're very welcome - I will make a more in depth reply ASAP

**Comment by poine** [comment]
here is a picture of the hardware - you can see that it is minoimalist
https://github.com/poine/rosmip

**Comment by AlejandroSilvestri** [comment]
Thank you very much!
